print('testing error')
raise Exception('some test error')